name: E2E-arm64
on:
  schedule:
  - cron: '30 1 * * *' # runs daily at 1am.
permissions: read-all
jobs:
  test:
    if: github.repository == 'etcd-io/etcd'
    runs-on: [self-hosted, Linux, ARM64]
    container: golang:1.19-bullseye
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-arm64-e2e
    steps:
    - uses: actions/checkout@v2
    - run: git config --system --add safe.directory '*'
    - id: goversion
      run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.goversion.outputs.goversion }}
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail
          go clean -testcache

        echo "${TARGET}"
        case "${TARGET}" in
          linux-arm64-e2e)
            PASSES='build e2e' GOOS=linux GOARCH=arm64  CPU='4' EXPECT_DEBUG='true' COVER='false' RACE='true' ./test.sh
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
